name: ci-tests

on:
  # Trigger on pull requests that target the following branches
  pull_request:
    branches:
      - 'main'
      - 'prerelease/**'
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        HELIUM_IS_RELEASE: 'false'
      run: ./gradlew ci
